name: Run Tests

on:
  push:
    branches:
      - "improve-algorithm"
  pull_request:
    branches:
      - "improve-algorithm"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run tests
        run: deno test